### ISSUE TITLE
ASCII 0 may be too narrow

### ISSUE THREAD

**Issue by eldstal** [dikey0ficial/zero#3]
While `0` could be expected to fill the half of the value space not covered by google's `1`©, a number of unicode confusables could be used to circumvent the copyleft license on `0`.

I propose that the following UTF codepoints be added, in order to also cover cases that normalize to `0`:

```text
₀ (U+2080)
𝟢 (U+1d7e2)
⓪ (U+24ea)
𝟬 (U+1d7ec)
𝟎 (U+1d7ce)
⁰ (U+2070)
０ (U+ff10)
𝟶 (U+1d7f6)
𝟘 (U+1d7d8)
```

**Comment by dikey0ficial** [comment]
Good idea! Also, should I add \0 symbol?
