### ISSUE TITLE
create automated workflow to push any and all new 0 types to language types

### ISSUE THREAD

**Issue by FCLC** [dikey0ficial/zero#6]
Concept is to use #4 in addition to commit https://github.com/dikey0ficial/zero/commit/ee6e7e89f0f231b54eeea2d8788a2bff0a573a88 as a master file. 

Create 2 files: Zero.types and languages.extensions. 

have an action/bash script etc. periodically verify for any new additions to either list. if either list is changed, create a new file of extension .lang for each of .types

As of this issue, 10 zero types are in the repo, and 7 languages have been added

**Comment by dikey0ficial** [comment]
I think that code should work, so this idea won't work automaticly with modt of languages)
